config/routes.rb
UrlShortener::Application.routes.draw do

  resources :urls
  root 'static_pages#home'
  get '/api', to: 'static_pages#api'
  get '/random', to: 'static_pages#random'
  post '/random', to: 'static_pages#random'
  get '/:id', to: 'urls#open_link'

end

app/models/url.rb
class Url < ActiveRecord::Base
  validates :alias, uniqueness: true, presence: true, length: { in: 1..100 }
  validates :link, presence: true, length: { maximum: 10_000 }

  scope :published, -> { where(public: true) }
  scope :pagination, ->(page, limit) { paginate(page: page, per_page: limit || 10) }
  scope :url_alias, ->(id) { find_by(alias: id) }

  before_save :snake_url

  def snake_url
    self.alias.strip!
    return nil if self.alias.empty?
    return self.alias = 'lomai_dalwe' if self.alias.index(/urls|api|random/)
    self.alias.to_s.gsub!(/\W/, '_')

    if self.alias.count('a-zA-Z0-9') > 0
      self.alias = self.alias[0..self.alias.rindex(/[a-zA-Z0-9]/)]
      self.alias = self.alias[self.alias.index(/[a-zA-Z0-9]/)..-1]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  respond_to :html, :js, only: :random

  def home
    @url = Url.new
  end

  def api
  end

  def random
    @url = Url.published.sample
    respond_with @url
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :open_link]
  respond_to :html, only: :create

  def index
    @urls = Url.published.pagination(params[:page], params[:limit])
  end

  def new
    @url = Url.new
  end

  def show
  end

  def open_link
    redirect_to @url.link
  end

  def create
    @url = Url.new(url_params)

    respond_with do |format|
      if @url.save
        format.html { redirect_to url_path(@url.alias), notice: 'Url was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  private

  def set_url
    @url = Url.url_alias(params[:id])
  end

  def url_params
    params.require(:url).permit(:link, :alias, :public, :ip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'URLShortener'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def simple_header(header)
    header && !header.empty? ? header : 'URLShortener'
  end

  def full_link(host, name)
    host = host.to_s
    host[0, host[host.index('//') + 2..-1].index('/') + 8] + name.to_s
  end
end

app/helpers/urls_helper.rb
module UrlsHelper
  def big_link(link)
    link.length < 100 ? link : nil
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert primary">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "URLShortener", request.url %>
    by <%= link_to "Henb", "https://coderbits.com/henb" %>
  </small>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navigation-bar">
   <ul class="brand-section">
     <li class="brand-name">
      <a href="/" class="menu-trigger" id="trigger">UrlShortener</a>
     </li>
     <li class="menu-toggle">
      <a href="#">Menu</a>
     </li>
   </ul>
   <ul class="pull-right">
     <li class="divider"></li>
     <li><%=link_to "Shortener URL", root_path%></li>
     <li class="divider"></li>
     <li><%=link_to "URLs", urls_path%></li>
     <li class="divider"></li>
     <li><%=link_to "Random", random_path%></li>
     <li class="divider"></li>
     <li><a href="<%= api_path %>" class="button danger">API<i class="fa fa-chevron-circle-right"></i></a></li>
   </ul>
</nav>

app/views/layouts/application.html.erb
<html lang="en">

<head>
  <!--includes meta tags, title and more header definitions-->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no">
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">

  <title><%= full_title(yield(:title)) %></title>

  <!-- Furatto core CSS -->
  <%= stylesheet_link_tag "application", :cache => true %>
  <%= csrf_meta_tag %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>
  <%= render "layouts/navbar"%>

  <div class="row">
    <div class="col-12 text-center">
    </div>
    <div class="row">
      <div class="col-2 text-center"></div>
          <div class="col-8">
            <%=render"layouts/flash"%>
            <h3><%= simple_header(yield(:title)) %></h3>
            <hr />
            <%= yield %>
          </div>
      <div class="col-2 text-center"></div>
    </div>
  </div>

  <%= render "layouts/footer"%>
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/static_pages/api.html.erb
<% provide(:title, "API") %>

<p>Project provides a simple JSON endpoint for every url. It is accessed by issuing an HTTP GET request to the profile URL with .json added to the end.</p>
<p class="label"><%= full_link request.url,"urls/my_url.json" %></p>

<p>Here is an example response for a URLShortener API request. </p>
<p class="label"><%= full_link request.url,"urls.json"%></p>

<br />

<p class="label">
  [<br>
    {"link":"http://api.rubyonrails.org/","alias":"rubyapi"},<br>
    {"link":"http://rubyonrails.org/","alias":"ror"},<br>
    {"link":"http://ruby-doc.org/","alias":"doc"}<br>
  ]
</p>

app/views/static_pages/home.html.erb
<p>This URLShortener the fastest URL shortener!</p>
<font class="button danger">Link</font> <font class="button">https://translate.google.by/#en/ru/Languages%0ALanguagegfdsdfgdfgg</font>
<br/>
<font class="button success">Result</font> <font class="button"><%= request.url %>mylink</font>
<hr/>
<%= render partial:"urls/form", locals:{url: @url} %>

app/views/static_pages/random.html.erb
<% provide(:title, "Random URL") %>
<center>
  <font class="button danger">API</font> <font class="button"><%= full_link request.url,"random.json" %></font>
  <hr/>
  <% if @url %>
    <h1>Your random URL</h1>
    <div class="link">
      <p> <%=link_to full_link(request.url, @url.alias), @url.link %></p></br>
    </div>
    <%= button_to "Get URL", random_path, remote: true, class: "button large" %>
  <% else %>
    <h1>Not found</h1>
  <% end %>
</center>

app/views/static_pages/random.js.erb
$('.link').empty();
$('.link').prepend('<p> <%=link_to(full_link(request.url, @url.alias), @url.link) %></p></br>');

app/views/urls/_form.html.erb
<%= form_for(url) do |f| %>
  <% if url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% url.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br>
    <%= f.url_field :link, placeholder:"Enter your big url" %>
  </div>
  <div class="field">
    <%= f.label :alias %><br>
    <%= f.text_field :alias, placeholder:"Enter alias for url" %>
  </div>

  <div class="field">
    <%= f.label :public %> <%= f.check_box :public, checked:true %>
  </div>

   <%= f.hidden_field :ip, value:request.remote_ip %>


  <div class="actions">
    <%= f.submit value:"Shortener URL", class:"button large" %>
  </div>
<% end %>

app/views/urls/index.html.erb
<% provide(:title, "Listing URLs") %>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Alias</th>
      <th>Action</th>

    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%=link_to(truncate(url.link,length:60),url.link) %></td>
        <td><%= truncate(url.alias,length:30) %></td>
        <td><%= link_to 'Show', url_path(url.alias), class:"pagination center" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<center>
<%= will_paginate @urls  %>
<br>
<%= link_to 'New URL', new_url_path,class:"button large" %>
</center>

app/views/urls/new.html.erb
<% provide(:title, "New URL") %>

<%= render partial:"urls/form", locals:{url: @url} %>

<%= link_to 'Back', urls_path,class:"button large" %>

app/views/urls/show.html.erb
<% provide(:title, "Shortener URL") %>

<p>
  <b class="label">Link</b>
  <%= link_to((big_link(@url.link) ? @url.link : "Big Link"),@url.link) %>
</p>

<p>
  <b class="label">Alias</b>
  <%=link_to full_link(request.url,@url.alias),full_link(request.url,@url.alias) %>
</p>

<%= link_to 'Back', urls_path,class:"button large"  %>